name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          persist-credentials: false
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          submodules: true
          fetch-depth: 0

      - uses: actions/cache@master
        id: node-modules
        with:
          path: node_modules/
          key: ${{ runner.os }}-node-modules-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      - name: Install Deps
        if: steps.node-modules.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile

      # 构建项目并
      - name: Build and zip
        run: |
          yarn run build
          cd ./vuepress
          zip -r dist.zip dist
        env:
          LEANCLOUD_APP_ID: ${{ secrets.LEANCLOUD_APP_ID }} # 评论系统的ID
          LEANCLOUD_APP_KEY: ${{ secrets.LEANCLOUD_APP_KEY }} # 评论系统的KEY

      # 部署到gh-pages分支
      - name: Deploy To gh-pages
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: .vuepress/dist

      - name: Scp file to aliyun
        uses: appleboy/scp-action@master
        with:
          # IP地址
          host: ${{ secrets.ALIYUN_SERVER_IP }}
          # 用户，如：root等
          username: ${{ secrets.ALIYUN_SERVER_USERNAME }}
          # 密码
          password: ${{ secrets.ALIYUN_SERVER_PASSWORD }}
          # ssh端口，如：22
          port: ${{ secrets.ALIYUN_SERVER_PORT }}
          source: "dist.zip"
          # 将文件拷贝到服务器
          target: "/home"

      - name: Backup and unzip
        uses: appleboy/ssh-action@master
        with:
          # IP地址
          host: ${{ secrets.ALIYUN_SERVER_IP }}
          # 用户，如:root等
          username: ${{ secrets.ALIYUN_SERVER_USERNAME }}
          # 密码
          password: ${{ secrets.ALIYUN_SERVER_PASSWORD }}
          # ssh端口，如：22
          port: ${{ secrets.ALIYUN_SERVER_PORT }}
          # 先备份再解压
          script: |
            cd /home
            echo "################# files moving #################"
            if [ -f "/home/reco-demo-bak" ];then
              rm -rf /home/reco-demo-bak
              echo "reco-demo-bak exists and is deleted"
            fi

            if [ -f "/home/reco-demo" ];then
              mv /home/reco-demo /home/reco-demo-bak
              echo "reco-demo exists and is backuped"
            fi

            unzip -d  /home/reco-demo /home/dist.zip
