name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy-gh-pages:
    runs-on: ubuntu-latest
    steps:
      # 获取源码
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          submodules: true
          fetch-depth: 0
      # 缓存依赖项配置
      - uses: actions/cache@v2
        id: node-modules
        with:
          path: node_modules/
          key: ${{ runner.os }}-node-modules-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-
      # 安装依赖
      - name: Install Deps
        if: steps.node-modules.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile

      # 构建项目并压缩为dist.zip
      - name: Build and zip
        run: |
          yarn run build
          cd .vuepress
          zip -r demo.zip ./dist
        env:
          LEANCLOUD_APP_ID: ${{ secrets.LEANCLOUD_APP_ID }} # 评论系统的ID
          LEANCLOUD_APP_KEY: ${{ secrets.LEANCLOUD_APP_KEY }} # 评论系统的KEY

      # 部署到gh-pages分支
      - name: Deploy To gh-pages
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: .vuepress/dist

      # Scp脚本拷贝dist.zip到服务器
      - name: Scp file to aliyun
        uses: appleboy/scp-action@master
        with:
          # IP地址
          host: ${{ secrets.ALIYUN_SERVER_IP }}
          # 用户，如：root等
          username: ${{ secrets.ALIYUN_SERVER_USERNAME }}
          # 密码
          password: ${{ secrets.ALIYUN_SERVER_PASSWORD }}
          # ssh端口，如：22
          port: ${{ secrets.ALIYUN_SERVER_PORT }}
          source: ".vuepress/demo.zip"
          # 将文件拷贝到服务器
          target: "/home/tmp"

      # 备份、解压、删除
      - name: Backup and unzip
        uses: appleboy/ssh-action@master
        with:
          # IP地址
          host: ${{ secrets.ALIYUN_SERVER_IP }}
          # 用户，如:root等
          username: ${{ secrets.ALIYUN_SERVER_USERNAME }}
          # 密码
          password: ${{ secrets.ALIYUN_SERVER_PASSWORD }}
          # ssh端口，如：22
          port: ${{ secrets.ALIYUN_SERVER_PORT }}
          # 先备份再解压
          script: |
            echo "################# files remove #################"
            if [ -f "/home/web/reco-demo-bak" ];then
              rm -rf /home/web/reco-demo-bak
              echo "reco-demo-bak exists and is deleted"
            fi
            echo "################# files backup #################"
            if [ -f "/home/web/reco-demo" ];then
              mv /home/web/reco-demo /home/web/reco-demo-bak
              echo "reco-demo exists and is backuped"
            else
              mkdir /home/web/reco-demo
            fi
            echo "################# unzip dist.zip #################"
            unzip -od  /home/web/reco-demo /home/tmp/demo.zip
